model_list:
  - model_name: qwen
    litellm_params:
      model: ollama/qwen2.5-coder:1.5b
      api_base: http://host.containers.internal:11434

  - model_name: gemini
    litellm_params:
      model: gemini/gemini-flash-latest
      api_key: os.environ/GEMINI_API_KEY

  - model_name: qwen-32b
    litellm_params:
      model: groq/qwen/qwen3-32b
      api_key: os.environ/GROQ_API_KEY

  - model_name: llama-scout
    litellm_params:
      model: groq/meta-llama/llama-4-scout-17b-16e-instruct
      api_key: os.environ/GROQ_API_KEY
