global:
  scrape_interval: 5m

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['10.86.6.10:9090']
  - job_name: 'intel-node'
    static_configs:
      - targets: ['host.containers.internal:9100']
  - job_name: 'oracle-node'
    static_configs:
      - targets: ['129.153.185.116:8099']
  - job_name: 'ryzen-node'
    static_configs:
      - targets: ['192.168.1.62:9100']
